const $=(s,root=document)=>root.querySelector(s), $$=(s,root=document)=>[...root.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let config={},media=[],chatBusy=false;
let db, records=[],relations=[], map,points, lines, boundary,selectedId='ZJCD-NB-003', currentView='home', cityFilter=new Set(),typeFilter=new Set(),query='',guideTab=0,explorePage=0;
const cities=['嘉兴市','绍兴市','宁波市','舟山市','台州市','温州市'];
const cityColors=['#667985','#879ca9','#52616a','#7896a1','#6d8792','#89959d'];
const categories=['军事聚落体系','烽传体系','沿海防御体系','内陆防御体系','社会人文'];
const get=id=>records.find(r=>r['遗产ID']===id),hasCoord=r=>Number.isFinite(r['经度'])&&Number.isFinite(r['纬度'])&&r['经度']>=-180&&r['经度']<=180&&r['纬度']>=-90&&r['纬度']<=90;
const summary=r=>r['遗址概况']||(config.distribution==='public-metadata'?'公开版展示遗址基础信息；研究原文尚未公开。':null)||'遗址概况尚未补充。可在详情页查看原表历史沿革与数据状态。';
const heading=(k,title,desc)=>`<div class="page-top"><div><div class="eyebrow">${k}</div><h1>${title}</h1><p class="lead">${desc}</p></div><span class="tag outline">开源研究平台</span></div>`;
function filtered(){return records.filter(r=>(!cityFilter.size||cityFilter.has(r['地级行政区']))&&(!typeFilter.size||typeFilter.has(r['海防体系']))&&(!query||[r['遗址名称'],r['遗产ID'],r['区县'],r['遗产二级类型'],r['详细地址']].join(' ').toLowerCase().includes(query.toLowerCase())))}
function navigate(view){if(map){map.remove();map=null} currentView=view;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(location.hash!=='#'+view)history.replaceState(null,'','#'+view);({home:homeView,map:mapView,explore:exploreView,history:historyView,system:systemView,ai:aiView,game:gameView,guide:guideView,learn:learnView,gesture:gestureView}[view]||mapView)();window.scrollTo(0,0)}
document.addEventListener('click',e=>{const n=e.target.closest('[data-view]');if(n){e.preventDefault();if(n.hasAttribute('data-reset-filters')){query='';cityFilter.clear();typeFilter.clear();explorePage=0}navigate(n.dataset.view)}const d=e.target.closest('[data-detail]');if(d)showDetail(d.dataset.detail)});
$('.close').onclick=()=>$('#detail').close();$('#detail').addEventListener('close',()=>history.replaceState(null,'','#'+currentView));$('#detail').addEventListener('click',e=>{if(e.target===$('#detail'))$('#detail').close()});
function filterRows(values,key,active){return values.map(v=>`<label class="filter-row"><input type="checkbox" data-filter="${key}" value="${esc(v)}" ${active.has(v)?'checked':''}><span>${esc(v)}</span><span class="count">${records.filter(r=>r[key]===v).length}</span></label>`).join('')}
function mapView(){if(typeof L==='undefined'){$('#main').innerHTML='<section class="page"><h1>地图组件暂未加载</h1><p>仍可打开遗产档案与资料检索。请检查网页文件是否完整。</p><button class="primary" data-view="explore">打开遗产档案</button></section>';return;} $('#main').innerHTML=`<div class="workspace"><aside class="filters"><div class="eyebrow">EXPLORE THE COAST</div><div class="section-label" style="margin-top:12px">⌕ 遗产筛选</div><input id="map-search" class="search" aria-label="搜索遗产" placeholder="搜索遗址、区县、类型…" value="${esc(query)}"><div class="filter-groups"><div><div class="section-label">按地级区域</div>${filterRows(cities,'地级行政区',cityFilter)}</div><div><div class="section-label">按海防体系</div>${filterRows(categories,'海防体系',typeFilter)}</div></div><button id="reset" class="reset">↺ 清空筛选条件</button><div class="section-label">图层控制</div><label class="filter-row"><input id="boundary-toggle" type="checkbox" checked>行政区边界</label><label class="filter-row"><input id="relations-toggle" type="checkbox">原表包含 / 隶属关系</label><p class="subtle">原表关系未区分遗产组成与军事隶属，不解释为历史指挥网络。</p></aside><section class="map-shell" aria-label="浙东海防遗产交互地图"><div id="map"></div><div class="map-caption"><span id="map-count"></span> · 滚轮缩放 / 拖动平移</div><div class="north">N<b>↑</b></div><div class="map-notice">原表坐标系与精度待核 · 仅供分布审阅</div></section><aside class="info"><div class="stats"><div><strong>${records.length}</strong><small>条遗产记录</small></div><div><strong>${records.filter(hasCoord).length}</strong><small>条有坐标</small></div></div><div class="selected" id="selected"></div><div class="legend"><strong>图例说明</strong><p><span><i class="dot ring"></i>卫城</span><span><i class="dot"></i>其他遗存</span></p><p>颜色区分六市 · 大小仅区分类别<br>虚线：原表关系（待复核）</p><p>${records.filter(r=>!hasCoord(r)).length} 条无坐标记录仍可在「遗产探索」阅读。重合点位请放大查看。</p><button class="secondary" data-view="explore" data-reset-filters>查看全部记录 →</button></div></aside></div><div class="entries"><button class="entry" data-view="history"><span class="num">01</span><strong>历史舆图</strong><small>从已登记的史料文件，连接遗址与历史空间。</small></button><button class="entry" data-view="system"><span class="num">02</span><strong>海防体系</strong><small>查看原表 ${relations.length} 条关系，辨别包含与隶属。</small></button><button class="entry" data-view="ai"><span class="num">03</span><strong>Heritage AI</strong><small>检索原表内容，带着依据理解海防遗产。</small></button><button class="entry" data-view="game"><span class="num">04</span><strong>互动学习</strong><small>用一次功能配对，认识不同海防设施。</small></button></div>`;
 map=L.map('map',{zoomControl:false,minZoom:6,maxZoom:17}).setView([29.05,121.1],7);L.control.zoom({position:'bottomright'}).addTo(map);L.control.scale({imperial:false,position:'bottomleft'}).addTo(map);map.attributionControl.setPrefix('Leaflet');map.attributionControl.addAttribution('边界：阿里云 DataV（概览） | 点位：用户工作簿，坐标系待核');
 boundary=L.geoJSON(db.boundary,{style:f=>({color:'#aabcc7',weight:1,fillColor:cities.includes(f.properties.name)?'#edf2f5':'#e2e9ee',fillOpacity:.95})}).addTo(map);
 if(!db.boundary.features.length&&location.protocol!=='file:'){const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors' }).addTo(map);tiles.on('tileerror',()=>{const n=$('.map-notice');if(n)n.textContent='底图加载受限；原表点位仍可查看，坐标系待核。'});}
 db.boundary.features.forEach(f=>{const c=f.properties.centroid||f.properties.center;if(c)L.marker([c[1],c[0]],{interactive:false,icon:L.divIcon({className:'city-label',html:esc(f.properties.name),iconSize:[65,20]})}).addTo(map)});
 L.marker([28.8,122.15],{interactive:false,icon:L.divIcon({className:'city-label',html:'东 海<br><small>East China Sea</small>',iconSize:[120,40]})}).addTo(map);points=L.layerGroup().addTo(map);lines=L.layerGroup().addTo(map);renderPoints();renderSelected();
 $('#map-search').oninput=e=>{query=e.target.value;renderPoints()};$$('[data-filter]').forEach(c=>c.onchange=()=>{const target=c.dataset.filter==='地级行政区'?cityFilter:typeFilter;c.checked?target.add(c.value):target.delete(c.value);renderPoints()});$('#reset').onclick=()=>{query='';cityFilter.clear();typeFilter.clear();$('#map-search').value='';$$('[data-filter]').forEach(c=>c.checked=false);renderPoints()};$('#boundary-toggle').onchange=e=>e.target.checked?boundary.addTo(map):map.removeLayer(boundary);$('#relations-toggle').onchange=renderPoints;
}
function renderPoints(){points.clearLayers();lines.clearLayers();const f=filtered(),shown=f.filter(hasCoord);$('#map-count').textContent=`${shown.length} 个点位 / ${f.length} 条匹配记录`;if(!f.some(r=>r['遗产ID']===selectedId))selectedId=f[0]?.['遗产ID']??'';for(const r of shown){const active=r['遗产ID']===selectedId,isWei=r['遗产二级类型']==='卫城';const marker=L.circleMarker([r['纬度'],r['经度']],{radius:active?10:isWei?7:4.5,color:active?'#1e2022':cityColors[cities.indexOf(r['地级行政区'])]||'#52616a',weight:isWei||active?2:1.5,fillColor:isWei?'#fff':cityColors[cities.indexOf(r['地级行政区'])]||'#52616a',fillOpacity:.92});marker.bindTooltip(esc(r['遗址名称']));marker.on('click',()=>{selectedId=r['遗产ID'];renderPoints();renderSelected()});marker.addTo(points);if(active)L.marker([r['纬度'],r['经度']],{interactive:false,icon:L.divIcon({className:'site-label',html:esc(r['遗址名称']),iconSize:[150,20],iconAnchor:[-15,10]})}).addTo(points)}
 if($('#relations-toggle').checked){const ids=new Set(shown.map(r=>r['遗产ID']));relations.forEach(r=>{const a=get(r['上级遗址ID']),b=get(r['子遗址ID']);if(a&&b&&ids.has(a['遗产ID'])&&ids.has(b['遗产ID'])&&hasCoord(a)&&hasCoord(b))L.polyline([[a['纬度'],a['经度']],[b['纬度'],b['经度']]],{color:'#7a839e',weight:1.5,dashArray:'5 6'}).bindTooltip('原表包含/隶属 · 待复核').addTo(lines)})}renderSelected()}
function renderSelected(){const r=get(selectedId);if(!r){$('#selected').innerHTML='<h2>没有匹配记录</h2><p>请调整搜索词或清空筛选条件。</p>';return}$('#selected').innerHTML=`<span class="eyebrow">SELECTED HERITAGE</span><h2>${esc(r['遗址名称'])}</h2><span class="tag">${esc(r['遗产二级类型'])}</span><p>${esc(summary(r).slice(0,100))}${summary(r).length>100?'…':''}</p><dl>${[['地级行政区',r['地级行政区']],['区县',r['区县']],['年代',r['年代原文']],['记录层级',r['记录层级']],['点位状态',hasCoord(r)?'已有坐标 · 待核':'尚无坐标']].map(([a,b])=>`<div><dt>${a}</dt><dd>${esc(b||'待补')}</dd></div>`).join('')}</dl><button class="primary" data-detail="${esc(r['遗产ID'])}">阅读遗产档案 ↗</button>`}
function showDetail(id){const r=get(id);history.replaceState(null,'','#heritage/'+encodeURIComponent(id));if(!r)return;const rel=relations.filter(x=>x['上级遗址ID']===id||x['子遗址ID']===id);$('#detail-body').innerHTML=`<div class="eyebrow">${esc(id)}</div><h2>${esc(r['遗址名称'])}</h2><span class="tag">${esc(r['遗产二级类型'])}</span> <span class="tag outline">${esc(r['数据审核状态'])}</span><dl>${[['行政区',`${r['地级行政区']} · ${r['区县']||'待补'}`],['地址',r['详细地址']],['年代原文',r['年代原文']],['文保级别',r['文保级别']||'原表未填'],['记录层级',r['记录层级']],['坐标',hasCoord(r)?`${r['经度']}, ${r['纬度']}（坐标系待核）`:'未提供']].map(([a,b])=>`<div><dt>${a}</dt><dd>${esc(b||'待补')}</dd></div>`).join('')}</dl><h3>遗址概况</h3><p>${esc(r['遗址概况']||(config.distribution==='public-metadata'?'此版本未公开原文摘录。':'原表暂缺遗址概况。'))}</p><h3>历史沿革</h3><p style="white-space:pre-wrap">${esc(r['历史沿革']||(config.distribution==='public-metadata'?'此版本未公开研究沿革文本。':'原表暂缺历史沿革。'))}</p><h3>保存现状与图像</h3><p>${esc(r['保存现状']||'原表尚未填写保存现状。')}</p><p>现状照片登记：${esc(r['现状照片']||'无')}<br>史料 / 舆图登记：${esc(r['关联史料/舆图文件（现有）']||'无')}</p>${rel.length?`<h3>原表关系 · ${rel.length} 条</h3>${rel.map(x=>`<p>${esc(x['上级遗址名称'])} → ${esc(x['子遗址名称'])}<br><small>包含/隶属 · 待复核</small></p>`).join('')}`:''}<div class="note">来源：上传工作簿「01_遗产主表」，遗产 ID ${esc(id)}；原表行号 ${esc(r['原表行号'])}。本页保留原表信息，不代表已完成史实审核。未知值不自动补写。</div><div class="dialog-actions">${hasCoord(r)?'<button id="locate" class="primary">在地图中定位</button>':''}<button id="ask-record" class="secondary">检索这处遗产的资料</button><button id="copy-record" class="secondary">复制档案链接</button></div>`;
 if(!$('#detail').open)$('#detail').showModal();$('#copy-record').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);$('#copy-record').textContent='已复制链接'}catch{$('#copy-record').textContent='请复制浏览器地址栏中的链接'}};if($('#locate'))$('#locate').onclick=()=>{$('#detail').close();cityFilter.clear();typeFilter.clear();query='';selectedId=id;navigate('map');map.setView([r['纬度'],r['经度']],13)};$('#ask-record').onclick=()=>{$('#detail').close();navigate('ai');ask(r['遗址名称'])}}
function exploreView(){const f=filtered();$('#main').innerHTML=`<section class="page">${heading('HERITAGE COLLECTION','沿着海岸，走进遗产','城址、烽堠、炮台与人文遗存，共同构成海防历史的空间线索。全部记录均来自上传工作簿。')}<div class="toolbar"><input id="explore-search" class="search" aria-label="搜索档案" placeholder="输入遗址名称、区县或类型" value="${esc(query)}"><select id="city-select" aria-label="筛选城市"><option value="">全部城市</option>${cities.map(c=>`<option ${cityFilter.size===1&&cityFilter.has(c)?'selected':''}>${c}</option>`).join('')}</select><select id="type-select" aria-label="筛选海防体系"><option value="">全部体系</option>${categories.map(c=>`<option ${typeFilter.size===1&&typeFilter.has(c)?'selected':''}>${c}</option>`).join('')}</select><button id="export-records" class="secondary">导出筛选结果 CSV ↓</button><button id="explore-reset" class="secondary">清空筛选</button><span id="result-count" class="subtle"></span></div><div id="cards" class="grid"></div><div id="pagination" class="toolbar"></div></section>`;$('#type-select').onchange=e=>{typeFilter.clear();if(e.target.value)typeFilter.add(e.target.value);explorePage=0;renderCards()};$('#export-records').onclick=exportRecords;$('#explore-search').oninput=e=>{query=e.target.value;explorePage=0;renderCards()};$('#city-select').onchange=e=>{cityFilter.clear();if(e.target.value)cityFilter.add(e.target.value);explorePage=0;renderCards()};$('#explore-reset').onclick=()=>{query='';cityFilter.clear();typeFilter.clear();explorePage=0;exploreView()};renderCards()}
function renderCards(){const f=filtered(),max=Math.max(1,Math.ceil(f.length/12));explorePage=Math.min(explorePage,max-1);$('#result-count').textContent=`${f.length} 条匹配记录 · ${f.filter(hasCoord).length} 条有坐标${typeFilter.size?' · 体系：'+[...typeFilter].join('、'):''}${cityFilter.size>1?' · 城市：'+[...cityFilter].join('、'):''}`;$('#cards').innerHTML=f.length?f.slice(explorePage*12,explorePage*12+12).map(r=>`<article class="card"><div class="eyebrow">${esc(r['地级行政区'])} / ${esc(r['区县']||'区县待补')}</div><h2>${esc(r['遗址名称'])}</h2><span class="tag">${esc(r['遗产二级类型'])}</span> <span class="tag outline">${esc(r['年代原文']||'年代待补')}</span><p>${esc(summary(r).slice(0,100))}${summary(r).length>100?'…':''}</p><div class="card-bottom"><span class="subtle">${hasCoord(r)?'◉ 坐标待核':'○ 尚无坐标'}</span><button class="secondary" data-detail="${r['遗产ID']}">阅读档案 ↗</button></div></article>`).join(''):'<div class="empty">没有匹配记录，请调整筛选条件。</div>';$('#pagination').innerHTML=`<button id="prev" class="secondary" ${explorePage===0?'disabled':''}>上一页</button><span>${explorePage+1} / ${max}</span><button id="next" class="secondary" ${explorePage>=max-1?'disabled':''}>下一页</button>`;$('#prev').onclick=()=>{explorePage--;renderCards();window.scrollTo(0,0)};$('#next').onclick=()=>{explorePage++;renderCards();window.scrollTo(0,0)}}
function historyView(){const h=records.filter(r=>r['关联史料/舆图文件（现有）']);$('#main').innerHTML=`<section class="page">${heading('HISTORICAL CARTOGRAPHY','在舆图中，寻找时间的层次','先把一张图与一处遗址、一个版本、一个年代准确关联，再进行古今空间比较。')}<div class="note">当前有 ${h.length} 条记录登记了史料或舆图文件名，但 Excel 不包含这些图像文件。本页展示真实登记目录；古今叠加功能需要原图与配准信息，暂未启用。</div><div id="media-resources"></div><div class="grid">${h.map((r,i)=>`<article class="card"><div class="number">0${i+1}</div><h2>${esc(r['遗址名称'])}</h2><p>${esc(r['关联史料/舆图文件（现有）'])}</p><span class="tag outline">仅文件名 · 原图待接入</span><div class="card-bottom"><span class="subtle">${esc(r['地级行政区'])}</span><button class="secondary" data-detail="${r['遗产ID']}">关联遗址 ↗</button></div></article>`).join('')}</div><div class="split" style="margin-top:28px"><article class="card"><h2>一张图需要哪些信息？</h2><p>史料 ID、遗产 ID、图名、书名与版本、成图年代、卷次页码、收藏机构、图像文件地址、使用权限、配准状态与控制点误差。</p><button class="secondary" data-view="guide">查看制作步骤 →</button></article><article class="card"><h2>不是所有舆图都适合叠加</h2><p>写意舆图可能强调方位、等级与交通关系，而非比例。此类图适合并排阅读和热点注释；具备可识别控制点的图，再尝试地理配准与透明度叠加。</p></article></div></section>`;renderMediaCards();}
function renderMediaCards(){
 const target=$('#media-resources');if(!target||!media.length)return;
 target.innerHTML=`<h2>已接入的图像资源</h2><div class="grid">${media.map(m=>`<article class="card"><h3>${esc(m.title)}</h3><p>${esc(m.source||'出处待补')}</p><button class="secondary" data-media="${esc(m.id)}">放大阅读 ↗</button></article>`).join('')}</div><h2>原表文件登记</h2>`;
 $$('[data-media]').forEach(b=>b.onclick=()=>openMedia(b.dataset.media));
}
function openMedia(id){
 const m=media.find(x=>x.id===id);if(!m)return;let modal=$('#media-dialog');if(!modal){modal=document.createElement('dialog');modal.id='media-dialog';document.body.appendChild(modal);}
 const url=m.url;if(!/^(https:\/\/|media\/|data:image\/)/.test(url)||url.includes('..'))return;
 modal.innerHTML=`<button class="close" aria-label="关闭图像">×</button><h2>${esc(m.title)}</h2><p class="subtle">${esc(m.source||'出处待补')} · ${esc(m.license||'使用权限待核')}</p><label>缩放 <input type="range" min="100" max="300" value="100" id="media-zoom"> <span id="media-scale">100%</span></label><div class="media-stage"><img id="media-image" src="${esc(url)}" alt="${esc(m.title)}"></div><p class="subtle">图像阅读视图，未执行地理配准。HTTPS 外部图像需要联网。</p>`;
 $('.close',modal).onclick=()=>modal.close();$('#media-image').onerror=()=>{$('.media-stage',modal).textContent='图像文件无法读取，请核对资源地址和访问权限。'};
 $('#media-zoom').oninput=e=>{$('#media-image').style.width=e.target.value+'%';$('#media-scale').textContent=e.target.value+'%'};
 modal.showModal();
}
function systemView(){const groups=[...new Set(relations.map(r=>r['上级遗址ID']))];$('#main').innerHTML=`<section class="page">${heading('DEFENCE NETWORK','从单处遗址，到关联网络','先阅读工作簿已有的组成关系，再逐步补充不同历史时期的军事隶属、协防与通信关系。')}<div class="toolbar"><label for="group-select">选择上级遗址</label><select id="group-select">${groups.map(g=>`<option value="${esc(g)}">${esc(get(g)?.['遗址名称']||relations.find(r=>r['上级遗址ID']===g)['上级遗址名称'])}</option>`).join('')}</select><span class="subtle">全表 ${relations.length} 条关系 · 全部待复核</span></div><div id="relations-panel"></div><div class="note">“遗址群包含某炮台”与“某千户所在某年隶属某卫”是两种关系。原表使用“包含/隶属”的合并标签，尚不足以生成严谨的历时军事组织图。</div><div class="split"><article class="card"><h2>遗产组成关系</h2><p>回答“这个遗址群由什么组成”。适合连接群体档案与子遗址，不必等同于历史军事建制。</p></article><article class="card"><h2>历史军事关系</h2><p>回答“何时、何地、由谁统辖”。需要关系类型、起止时间、依据来源与置信度，不按地图邻近自动推导。</p></article></div></section>`;$('#group-select').onchange=renderRelations;renderRelations()}
function renderRelations(){const id=$('#group-select').value,rs=relations.filter(r=>r['上级遗址ID']===id);$('#relations-panel').innerHTML=`<div class="tree"><button class="tree-node active" data-detail="${esc(id)}">${esc(rs[0]['上级遗址名称'])}</button><div class="eyebrow" style="margin-top:20px">原表包含 / 隶属 · 待复核</div><div class="tree-children" style="flex-wrap:wrap">${rs.map(r=>`<button class="tree-node" data-detail="${esc(r['子遗址ID'])}">${esc(r['子遗址名称'])}</button>`).join('')}</div></div><p class="subtle">${rs.length} 条关联 · 来源：02_遗址关系表；关系由原始字段整理，未补写新的历史联系。</p>`}
function aiView(){
 $('#main').innerHTML=`<section class="page">${heading('HERITAGE AI','让每一次提问，都能回到资料','先检索已有材料，再阅读证据。可选模型问答通过独立后端启用。')}<div class="chat-layout"><aside><h2 style="font-family:var(--serif)">从一个问题开始</h2><p class="subtle">支持遗址名与短问题，如“观海卫城有什么历史”。</p>${['观海卫城有什么历史','乍浦','烽火台','炮台'].map(q=>`<button class="suggestion" data-question="${q}">${q} ↗</button>`).join('')}<label class="filter-row"><input id="use-model" type="checkbox">使用已配置的 AI 后端</label><label for="site-token" class="subtle">站点访问口令（若管理员设置）</label><input id="site-token" type="password" class="search" autocomplete="off" placeholder="不是模型 API 密钥"><div class="note">纯静态与离线版默认在本机检索，不发送资料。后端模式只向管理员配置的服务发送当前问题和相关资料。</div></aside><div class="chat-main"><div class="chat-title">◇ Heritage AI <span id="chat-mode" class="tag outline" style="float:right">本地资料检索</span></div><div class="chat-log" id="chat-log" role="log" aria-live="polite"><div class="message">你好，请输入你感兴趣的遗址或问题。结果会附原表 ID，可继续打开档案核对。<small>当前资料全部待复核，默认不用于模型生成确定结论。</small></div></div><form class="chat-form" id="chat-form"><input id="question" class="search" aria-label="输入问题" placeholder="例如：观海卫城有什么历史？" maxlength="500" required><button class="primary" id="chat-submit" type="submit">查询 ↗</button></form></div></div></section>`;
 $('#chat-form').onsubmit=e=>{e.preventDefault();const q=$('#question').value.trim();if(q&&!chatBusy){ask(q);$('#question').value=''}};
 $$('[data-question]').forEach(b=>b.onclick=()=>{if(!chatBusy)ask(b.dataset.question)});
 $('#use-model').onchange=e=>$('#chat-mode').textContent=e.target.checked?'后端问答':'本地资料检索';
}
function evidenceHtml(sources){return sources.map(r=>`<p><strong>${esc(r.name)}</strong><br>${esc(r.text.slice(0,500))}${r.text.length>500?'…':''}<small>${esc(r.source)} · ${esc(r.id)} · ${esc(r.status)}</small><button class="secondary" data-detail="${esc(r.id)}">阅读完整档案 ↗</button></p>`).join('')}
async function ask(q){
 if(chatBusy)return;chatBusy=true;const log=$('#chat-log'),u=document.createElement('div');u.className='message user';u.textContent=q;log.appendChild(u);
 const a=document.createElement('div');a.className='message';a.textContent='正在查找资料…';log.appendChild(a);const submit=$('#chat-submit');if(submit)submit.disabled=true;
 const useModel=$('#use-model')?.checked,token=$('#site-token')?.value||'';
 try{
  if(!useModel){const ranked=AtlasSearch.search(records,q,4).map(x=>AtlasSearch.evidence(x.record));a.innerHTML=ranked.length?`${config.distribution==='public-metadata'?'<small>公开版仅提供基础字段；研究原文尚未公开。</small>':''}找到 ${ranked.length} 条相关记录：${evidenceHtml(ranked)}<small>本地资料检索，未调用模型。请以原文与来源核验内容。</small>`:'没有找到相关记录。请换用准确的遗址名称或更短的关键词。';}
  else{
   if(location.protocol==='file:')throw Error('离线版不连接 AI 后端。请使用本地服务或配置后的在线站点。');
   const endpoint=config.aiEndpoint||new URL('api/chat',location.href.split('#')[0]).href;
   const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',...(token?{'Authorization':'Bearer '+token}:{})},body:JSON.stringify({question:q}),signal:AbortSignal.timeout(35000)});
   if(response.status===404||!String(response.headers.get('content-type')).includes('application/json'))throw Error('此地址尚未部署 AI 后端。GitHub Pages 仅运行静态网页；请取消勾选，继续本地检索。');
   const result=await response.json();if(!response.ok)throw Error(result.error||'后端请求失败。');
   a.innerHTML=`${result.answer?`<p>${esc(result.answer)}</p>`:''}<small>${esc(result.message||'')}</small>${evidenceHtml(result.sources||[])}`;
  }
 }catch(error){a.textContent=error.name==='TimeoutError'?'请求超时，请重试或使用本地检索。':error.message;}
 finally{chatBusy=false;if(submit)submit.disabled=false;log.scrollTop=log.scrollHeight;}
}
let selectedFacility='烽堠', placements={};
function gameView(){$('#main').innerHTML=`<section class="page">${heading('LEARN THROUGH PLAY','为海岸，安排一道防线','选择设施，再点击与其主要功能相符的位置。这里是功能教学示意，不代表真实遗址的空间复原。')}<div class="game-options">${['烽堠','炮台','城址'].map(x=>`<button data-facility="${x}" class="${x===selectedFacility?'active':''}">${x}</button>`).join('')}<button id="game-reset">↺ 重新安排</button></div><div class="game-slots">${[['高处观察点','观察远处动静，传递警报信息。','烽堠'],['海口防御点','以火力防御重要水道与海口。','炮台'],['驻防聚落','容纳驻防活动，并组织聚落空间。','城址']].map(([title,desc,answer],i)=>`<button class="slot" data-slot="${i}" data-answer="${answer}"><span class="eyebrow">0${i+1} / FUNCTION</span><b>${title}</b><p>${desc}</p><em>${esc(placements[i]||'点击放置已选设施 +')}</em></button>`).join('')}</div><div class="feedback" id="game-feedback" aria-live="polite">已选择「${selectedFacility}」。请点击一个功能位置。</div><p class="subtle">完成后可进入真实数据库，查找具有相应功能的遗址。具体设施的用途和变化，应以各遗址史料为依据。</p></section>`;$$('[data-facility]').forEach(b=>b.onclick=()=>{selectedFacility=b.dataset.facility;$$('[data-facility]').forEach(x=>x.classList.toggle('active',x===b));$('#game-feedback').textContent=`已选择「${selectedFacility}」。请点击一个功能位置。`});$$('[data-slot]').forEach(b=>b.onclick=()=>{if(selectedFacility===b.dataset.answer){placements[b.dataset.slot]=selectedFacility;$('em',b).textContent=`✓ 已安排：${selectedFacility}`;$('#game-feedback').innerHTML=Object.keys(placements).length===3?'三处功能已完成配对。下一步可到遗产数据库中查看真实案例。 <button id="game-explore" class="primary">探索相关遗存 ↗</button>':`「${selectedFacility}」与此处功能相符。继续选择另一类设施。`;if($('#game-explore'))$('#game-explore').onclick=()=>{query='';cityFilter.clear();typeFilter.clear();navigate('explore')}}else $('#game-feedback').textContent=`再想一想：「${selectedFacility}」的主要作用是否与这里的功能相符？提示：烽堠传警、炮台火力防御、城址承载驻防聚落。`});$('#game-reset').onclick=()=>{placements={};selectedFacility='烽堠';gameView()}}
const table=(headers,rows)=>`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const guideSections=[
['01','先理解整体',()=>`<h2>你要制作的，不只是一组页面</h2><p>你的工作是把文化遗产知识整理成可以查询、阅读和验证的内容；AI 帮你把这些规则写成网页。先做“一个遗址能被找到、读懂、追溯出处”的完整流程，再增加更复杂的交互。</p><h3>案例给我们的启发</h3><p>ArchCritic 公开页展示了“知识学习—案例理解—设计实践—AI 评图—反馈学习—版本修改”的闭环，也介绍了知识卡、案例库、知识测试与分阶段评审角色。值得借鉴的是内容之间的关联方式，而不是照搬建筑评图功能。</p>${table(['案例公开页可确认','转译为海防遗产网站'],[['知识卡与案例学习','概念词条 + 遗址档案；每个概念能跳到真实遗址'],['知识测试与反馈学习','功能配对游戏；完成后返回相关知识与记录'],['AI 评图后追问并返回知识','针对遗址提问；回答附证据，能打开原条目'],['版本修改与复盘','保留资料修订、审核和发布版本，区分新旧解释']])}<div class="note">实际访问范围：已查看案例公开介绍页和工作台登录入口。工作台需要账号登录；本次未注册账号、未登录内部功能。因此不能确认内部 GIS、小游戏或具体技术架构。以下技术方案是为你的项目提出的实现建议，不是对案例源码的识别。</div><h3>网页由六部分共同组成</h3>${table(['部分','可以怎样理解','你的项目需要什么'],[['内容与数据库','展览的藏品目录和说明文字','已有 Excel / 飞书多维表格，保留稳定遗产 ID'],['前端界面','观众能看到和操作的展厅','地图、列表、档案页、问答框、小游戏'],['后端服务','处理请求的工作人员','正式接入 AI、飞书同步、审核和权限时再加入'],['地理与媒体资源','地图、照片、扫描件的库房','地理文件与图像文件，分别保留出处和权限'],['AI 检索与回答','先翻资料、再回答的讲解员','文献分段、检索、生成、有据回答和引用跳转'],['发布与维护','开馆和日常管理','可访问网址、私有/公开范围、更新、备份与纠错']])}<p>本版支持 GitHub Pages、离线文件和本地 Node 服务。可选 AI 后端已提供，真实模型尚未配置；未接入实时飞书同步或多人编辑。</p>`],
['02','逐项拆解功能',()=>`<h2>每个功能，具体要准备什么？</h2>${table(['模块','你准备的内容','AI / 开发制作的部分','如何验收'],[['遗产探索','名称、ID、地区、类型、概况、审核状态','搜索、筛选、分页和档案详情','用遗址名能找到记录；空字段显示待补'],['GIS 地图','经纬度、坐标系、来源、定位精度；以后补范围线面','Leaflet 地图、点位点击、筛选联动与图例','坐标无效不上图；无坐标条目仍在列表；点与详情一致'],['历史舆图','原图、图名、版本、年代、收藏机构、页码、权限','第一步图像放大/注释；第二步并排；适合的图才地理叠加','能够回到原图和出处；不把古图畸变当真实空间变化'],['海防体系','起点 ID、终点 ID、关系类型、起止年代、依据','关系图、按时期筛选、点击节点打开档案','包含与军事隶属分开，不能用临近距离推导指挥关系'],['AI 互动问答','已审核的原文片段、来源页码、关联遗址 ID','后台检索资料后调用模型；生成引用与拒答','答案能打开证据；缺材料不编造；密钥只存后端'],['小游戏','学习目标、规则、反馈、对应知识条目','用网页交互先实现一款轻量游戏','手机也能操作；完成后有解释并链接真实遗址'],['后续扩展','明确新功能需要的输入与成果','再逐项增加故事路线、三维模型等','扩展不破坏已有 ID、链接和来源关系']])}<h3>不要一开始做多智能体</h3><p>案例的评审角色对应建筑设计的多个专业判断。你的第一版更需要准确的资料检索、清楚的出处与稳定的地图。先让一个问答流程可核查，再判断是否需要史料、空间与保护等不同角色。</p>`],
['03','用好现有数据库',()=>`<h2>你的 Excel 已经是开发起点</h2><p>无需推倒重建。现有工作簿已经包含主表、关系表、字段字典、枚举字典、质检、同名复核和原始数据，接下来重点是补证据与确认字段语义。</p>${table(['当前实测','数量 / 状态','对网页的影响'],[['遗产记录','282 条，六市','是记录数，不自动等于去重后的独立遗址数'],['有效数值坐标','163 条；坐标系、定位精度均待核','可预览分布，不能据此声称精确定位'],['无坐标','119 条','保留档案，不用城市中心伪装遗址位置'],['遗址概况','269 条有内容；13 条为空','观海卫城等仍需补简介；不把沿革静默替代概况'],['历史沿革','41 条有内容','扩充文献依据后再提高问答覆盖率'],['史料 / 舆图登记','6 条记录，只有文件名','登记不等于拥有网页可读取的图像资源'],['现状信息','保存现状 0 条；照片字段 2 条非空','不能声称已有现状图库或保护现状评价'],['时间信息','起始、终止年份均为空','暂不做精确年度时间筛选，不把朝代自动变成年份'],['数据关系','48 条，合并标为包含/隶属','先展示原表关系，不解释为历史组织网络'],['审核与重复','282 条待复核；4 组同名待核；182 条质检事项','保留质检清单，不自动合并同名或近邻记录']])}<h3>优先完成这五件事</h3><ol><li>先选 10–20 条重点遗址完成“名称—概况—坐标—图片—来源”的完整链条。</li><li>核验坐标来源与坐标系，特别是地图搜索点是否落在遗址本体、入口、纪念设施或相邻地标。</li><li>给主表关联一张“证据/史料表”，不要继续把书名、页码与整段沿革塞在同一格。</li><li>把图片文件名替换为可访问的附件资源，并保留原始文件与使用权限。</li><li>把“可用于 GIS”改为更细的审核条件：有坐标、坐标系已知、位置已核。当前准备度标记不能代替位置审核。</li></ol><h3>保留的关联结构</h3>${table(['表','主要字段','用途'],[['遗产主表（已有）','遗产 ID、名称、地区、类型、概况、坐标、审核状态','所有页面都围绕同一个 ID 关联'],['关系表（已有，需细分）','起点/终点 ID、关系类型、时间、史料 ID、状态','分别表达组成、统辖、协防、通信等关系'],['证据/史料表（建议补）','证据 ID、遗产 ID、书名、版本、卷页、原文、解释、审核状态','支持详情引用、AI 回答、证据核验'],['图像/舆图表（建议补）','资源 ID、遗产 ID、文件地址、年代、出处、权限、配准信息','支持照片与舆图展示'],['知识与互动表（后续）','知识 ID、内容、关联遗址、游戏规则、解释、来源','学习、游戏和问答共享资料']])}<h3>飞书如何继续使用？</h3><p>把飞书作为你的整理与审核工作台。前期使用“导出 Excel → 校验 → 转换网页数据 → 发布新版本”的人工更新方式，容易检查与回滚。需要频繁更新后，再由后端通过飞书接口读取允许发布的记录；令牌不放到浏览器中。</p><p>本原型是这次 Excel 的快照。修改飞书不会自动改变此页面；也没有修改原工作簿里的“未发布”状态。</p>`],
['04','制作 GIS 与舆图',()=>`<h2>先把点位做对，再增加空间分析</h2><h3>GIS 的第一版</h3><ol><li>从主表提取 ID、名称、类型、经纬度及坐标质量字段。</li><li>核验原始坐标系。WGS84、GCJ-02、BD-09 不能只改字段名称就混用；来源未知时先标记待核，避免盲目转换。</li><li>使用 GeoJSON 表达点、线、面；坐标顺序是经度、纬度。Leaflet 直接添加点位时常用纬度、经度，需要注意两种顺序。</li><li>将点击点位与遗产 ID 关联；筛选同时更新地图和列表，缺坐标的记录保留在档案库。</li><li>核对代表性点位后，再加入图层开关、范围面、按时期筛选等功能。</li></ol><p>本次网页使用 Leaflet 与本地保存的浙江行政区边界，不依赖在线瓦片即可展示点位。边界来自 DataV，作为空间概览；原表坐标系待核，二者叠加不代表已经完成坐标统一。</p><h3>历史舆图的两条制作路径</h3>${table(['图像特点','适合的做法','需要的材料'],[['以方位、路线、等级为主，比例失真较大','高分辨率查看、热点注释、与现代地图并排阅读','原图 + 文献说明 + 热点位置与解释'],['存在多个可靠且可识别的空间控制点','先在 GIS 软件做地理配准，再叠加到网页并调透明度','原图 + 控制点 + 目标坐标系 + 配准方法/误差记录']])}<p>不要直接把古图拉伸到现代地图上就称为“古今精确对照”。沿岸岸线、地名和城址边界都可能改变，配准结果需要解释。</p><h3>进入正式公开展示前</h3><p>按实际服务地区核对底图授权、署名、地图展示要求与服务可达性，选定适合的底图来源。此原型为私有审阅用途，尚未完成公开地图发布所需核验。</p><p><a href="https://leafletjs.com/examples/geojson/" target="_blank" rel="noreferrer">Leaflet 官方 GeoJSON 教程 ↗</a> · <a href="https://leafletjs.com/reference.html" target="_blank" rel="noreferrer">Leaflet 官方参考文档 ↗</a></p>`],
['05','制作有依据的 AI',()=>`<h2>先让 AI 找到资料，再让它回答</h2><p>正式问答需要“检索增强生成”，也就是先从你整理的资料中找到相关段落，再把问题与这些段落一起交给模型。你不需要自己训练一个大模型。</p>${table(['步骤','你需要提供','网页背后执行的工作'],[['1. 整理证据','原文、遗产 ID、书名、版本、卷页、审核状态','将材料分成可独立理解的短片段，保留上下文'],['2. 建立索引','确定哪些材料可供问答使用','关键词检索；覆盖扩大后可结合向量语义检索'],['3. 检索相关内容','用户问题与当前遗址','选出相关证据，排除不相关或不允许使用的材料'],['4. 生成回答','回答规则：区分事实、解释、存疑','由后端调用模型，要求只依据检索证据回答'],['5. 展示引用','证据 ID、书名、卷页与原文','让读者一键返回证据卡或遗址详情'],['6. 核验效果','准备一组有答案、无答案和有争议的问题','检查引文真实性、遗漏、混淆与无依据生成']])}<h3>本次已实现什么？</h3><p>Heritage AI 页面当前是<strong>本地关键词检索</strong>，从工作簿的概况与历史沿革中返回原文摘录，并链接到完整记录。没有连接模型，不会冒充已经具备智能推理。</p><h3>下一步给开发 AI 的明确要求</h3><div class="prompt">为现有 Heritage AI 接入后端问答服务。先检索已审核证据，再调用模型。每条回答附有效证据 ID，引用点击后能看到原文及书名卷页。材料不足时明确说“现有材料无法回答”。把事实与解释分开，不新增无依据的年代、尺寸或隶属关系。密钥仅在服务器保存。加入请求失败提示、访问频率限制和用量记录。先用 20 个测试问题检验引用能否支撑回答，再扩大资料量。</div><p>启用外部模型前，由你选定服务与数据使用范围。未审核的原表摘录可以用于私有研究检索，但不应直接成为对公众作确定回答的权威依据。</p>`],
['06','游戏与学习闭环',()=>`<h2>小游戏的目的，是帮助理解</h2><p>先确定一个学习目标，而不是先找一款可以嵌入的游戏。第一版可以教“不同海防设施发挥什么作用”，完成后回到真实遗址阅读，这样交互才与研究内容相连。</p>${table(['层次','示例','制作方式'],[['第一版：小规则、直接操作','选择烽堠、炮台和城址，匹配主要功能','HTML / CSS / JavaScript 即可，不需要大型游戏引擎'],['第二版：带情境的学习','辨别不同设施，比较遗址记录，安排信号传递次序','把内容、判定和解释写成可维护的数据'],['以后：更复杂的空间互动','经证据支持的视线模拟或历史防御情境','准备地形、年代与设施信息；再判断是否需要三维或专用引擎']])}<h3>自己制作还是嵌入外部游戏？</h3><p>自己的轻量游戏更容易连接遗产 ID、学习解释和网站配色。如果外部游戏提供正式嵌入功能，可以在取得使用许可后使用 iframe；先检查手机操作、允许嵌入的域名、加载失败提示与数据收集方式。不能假设任意网址都能直接嵌入。</p><h3>学习闭环怎样形成</h3><p>知识卡介绍烽堠 → 到地图寻找具体遗址 → 阅读依据 → 完成功能游戏 → 查看解释 → 返回相关遗址继续学习。每一步都用遗产 ID 或知识 ID 连接，避免几个模块各自孤立。</p><button class="primary" data-view="game">体验功能配对 →</button>`],
['07','零基础实施顺序',()=>`<h2>按可验收的小步骤，和 AI 一起做</h2><p>你不必先学完整套编程。先学会分清内容、界面和服务；每次只让 AI 完成一个可以点击验证的功能。</p>${table(['阶段','具体行动','交付物与通过条件'],[['A · 完成数据小样','先核验 10–20 条重点遗址；补 ID、简介、坐标来源、证据、图像','每条都可追溯；相同 ID 能贯通各表'],['B · 完成档案与地图','把数据导入网页，制作筛选、列表、地图与详情','找到一个遗址，点击地图可打开对应档案；手机可读'],['C · 接入图像与史料','取得原图，补元数据；先做图像查看与并排阅读','文件可打开、来源可查，不虚构配准精度'],['D · 接入真正 AI','建立审核后的证据索引，加入后端模型调用','有依据的问题能回答；无依据问题不编造；引用有效'],['E · 加入学习游戏','先完成一款功能配对，再视需要扩展','规则清晰，错误有解释，结束能回到真实记录'],['F · 小范围试用再公开','邀请少量同学/老师评估；修订资料与交互','检查权限、资料授权、地图要求、密钥管理、备份与回滚']])}<h3>让 AI 修改网页时这样说</h3><div class="prompt">请在现有浙东海防遗产网站上继续修改，保留现有设计与遗产 ID。
本次只完成：【一个具体功能】。
数据来源：【工作表与字段名】；空白字段显示“待补”，不得编造。
用户操作：【点击什么 → 出现什么 → 能做什么】。
验收标准：【可以直接操作验证的 3–5 条要求】。
完成后告诉我哪些功能已真实接入、哪些仍是演示，以及我还需补充哪些资料。</div><h3>你可以自己验收的项目</h3><div class="progress-track"><div id="check-progress"></div></div><p id="check-count" class="subtle"></p><div class="checklist">${['输入“观海卫城”能找到唯一 ID 对应档案','点击一个地图点，名称与详情一致','搜索无坐标遗址时，列表中仍有记录','调整筛选后，数量、地图和列表口径一致','原表空值显示待补，没有被编造成资料','问答能返回原文和 ID，且明确当前是检索演示','小游戏在手机上也可以点选完成','明确哪些记录、图片与关系还未核验'].map((t,i)=>`<label><input type="checkbox" data-check="${i}">${t}</label>`).join('')}</div><p class="subtle">勾选仅记录在当前浏览器，不写回 Excel 或飞书。</p>`],
['08','本版范围与来源',()=>`<h2>当前版本：可独立部署的开源平台</h2>${table(['已经真实实现','尚待接入 / 核验'],[['Excel 主表 282 条记录，搜索、分页、详情与城市筛选','飞书实时同步、数据在线编辑与发布审批'],['163 个原表数值坐标点、地图平移缩放、图层开关','坐标系统一、定位实核、城址范围与历史时期筛选'],['48 条原表关系；节点关联档案','严格区分包含/隶属及关系的历史时间'],['6 条史料/舆图文件登记展示','原图文件、配准与古今叠加'],['本地检索、出处 ID、详情跳转及可选模型后端','真实模型账户、语义索引与经审核的卷页级证据'],['可操作的功能配对学习游戏','复杂历史情境、三维模型或严谨模拟']])}<h3>数据范围与署名</h3><div class="credits"><p>遗产内容：用户上传《浙东海防遗产开发数据库_飞书导入版.xlsx》。数据截至本次导入，未独立核验史实。原表中收录的第三方原文，正式对外发布前应确认使用方式；可优先整理为有出处的简明介绍。</p><p>范围：保留工作簿嘉兴、绍兴、宁波、舟山、台州、温州六市的既有记录，不据标题重新删改地理范围。282 为记录总数，包含遗址群、子遗址与待复核同名项。</p><p>关系和分类：来自原表自动整理字段；全部待复核。没有自动将相邻遗址连成军事网络。</p><p>坐标：163 条数值坐标有效；来源、坐标系和精度未确认。本版按原值预览，不提供精确空间结论。</p><p>地图实现：<a href="https://leafletjs.com/" target="_blank" rel="noreferrer">Leaflet</a>（BSD-2-Clause）；行政区边界：<a href="https://geo.datav.aliyun.com/areas_v3/bound/330000_full.json" target="_blank" rel="noreferrer">阿里云 DataV 浙江边界数据</a>。本地保存用于概览。</p><p>案例参考：<a href="https://archcritic.cn/" target="_blank" rel="noreferrer">ArchCritic 公开介绍页</a>。已观察公开学习闭环及登录入口，未查看受账号保护的内部页面。不推断其实际技术栈，也不将用户希望的 GIS 和游戏功能称为已核实的案例功能。</p></div><h3>新增内容组织参考</h3><p>参考<a href="https://bjaxiscloud.com.cn/expert/web/index.html" target="_blank" rel="noreferrer">北京中轴线官网</a>的分层导航、空间分段、构成要素、历史和导览组织方式，新增叙事首页、六市切换、专题阅读与舆图时空舱。仅借鉴内容组织，不复制其图像、文字或品牌风格。</p><h3>从你的配色中提取</h3><div class="swatches">${[['#F0F5F9','雾白'],['#C9D6DE','海雾蓝'],['#52616A','板岩灰'],['#1E2022','墨黑']].map(([c,n])=>`<div class="swatch" style="background:${c};color:${['#52616A','#1E2022'].includes(c)?'#fff':'#1e2022'}">${n}<br>${c}</div>`).join('')}</div><p>网页沿用上传设计的“左侧筛选—中央地图—右侧档案摘要”结构，辅以宋体标题和清晰的数据层级。没有把参考图中的静态地图和弹窗当成真实交互。</p><p class="subtle">设计沿用用户提供的配色和布局方向；统计按上传 Excel 计算。</p>`]
];
function guideView(){$('#main').innerHTML=`<section class="page">${heading('BUILDING YOUR HERITAGE ATLAS','从整理资料，到一个可用的网站','一份面向文化遗产学生的制作指南：理解各模块，知道先准备什么，再让 AI 按步骤实现。')}<div class="guide-layout"><aside class="guide-menu">${guideSections.map(([n,t],i)=>`<button data-guide="${i}" class="${guideTab===i?'active':''}">${n}　${t}</button>`).join('')}</aside><article class="guide-content" id="guide-content"></article></div></section>`;$$('[data-guide]').forEach(b=>b.onclick=()=>{guideTab=Number(b.dataset.guide);$$('[data-guide]').forEach(x=>x.classList.toggle('active',x===b));renderGuide()});renderGuide()}
function renderGuide(){$('#guide-content').innerHTML=(config.distribution==='public-metadata'?'<div class="note">这是公开精简快照。原文、图像和第三方边界已排除；本指南中的原始数据审阅统计描述完整研究工作簿。</div>':'')+guideSections[guideTab][2]();if(guideTab===6){let saved=[];try{saved=JSON.parse(localStorage.getItem('coastal-checklist')||'[]')}catch{}const update=()=>{const values=$$('[data-check]').filter(x=>x.checked).map(x=>Number(x.dataset.check));$('#check-count').textContent=`已自检 ${values.length} / 8 项`;$('#check-progress').style.width=`${values.length/8*100}%`;try{localStorage.setItem('coastal-checklist',JSON.stringify(values))}catch{}};$$('[data-check]').forEach(c=>{c.checked=saved.includes(Number(c.dataset.check));c.onchange=update});update()}}
let homeCity='宁波市';
function homeView(){
 const picture=media.find(m=>m.scope==='region');
 $('#main').innerHTML=`<section class="atlas-hero">${picture?`<img class="hero-map" src="${esc(picture.url)}" alt="用户仓库原有浙江舆图，作为历史空间阅读入口">`:''}<div class="hero-copy"><div class="eyebrow">A DIGITAL ATLAS OF COASTAL MEMORY</div><h1>从一张舆图，<br>读懂浙东海防。</h1><p>沿着海岸寻找城址与烽堠，<br>在遗存、史料与地方记忆之间，<br>阅读一片区域的历史。</p><div class="hero-actions"><button class="light-btn" data-view="map">进入地图视图 ↗</button><button class="text-btn" data-view="explore">浏览遗产档案 →</button></div><div class="hero-foot"><span>六市 / 海岸 / 地方社会</span><span>01 — 山海之间</span></div></div><button class="image-credit" data-view="history">浙江舆图 · 查看图像来源 ↗</button></section><section class="atlas-intro"><div><span class="eyebrow">HERITAGE IN CONTEXT</span><h2>遗产不止于一处城墙。<br>也在山海相连的空间里。</h2></div><div><p>以遗产档案为基础，从地理分布进入历史阅读，再通过史料、关系与互动学习理解不同类型的海防遗存。</p><div class="home-stats"><span><b>${records.length}</b>条遗产记录</span><span><b>${records.filter(hasCoord).length}</b>条有坐标</span><span><b>${cities.length}</b>个地级区域</span></div><small>研究快照 · 坐标与史料待复核</small></div></section><section class="regional-section"><div class="chapter-head"><div><span class="eyebrow">02 / REGIONAL EXPLORATION</span><h2>沿海六市，逐城阅读</h2></div><p>按工作簿既有范围组织 · 点击地区查看记录</p></div><div class="city-tabs" role="group" aria-label="选择城市">${cities.map((city,i)=>`<button data-home-city="${city}" class="${city===homeCity?'active':''}" aria-pressed="${city===homeCity}"><small>0${i+1}</small><strong>${city.replace('市','')}</strong><span>${records.filter(r=>r['地级行政区']===city).length} 条</span></button>`).join('')}</div><div id="home-city-records"></div></section><section class="reading-section"><div class="chapter-head"><div><span class="eyebrow">03 / WAYS OF READING</span><h2>换一个视角，理解海防</h2></div><button class="secondary" data-view="learn">进入知识学习 ↗</button></div><div class="reading-grid"><button data-view="system"><span>一 / 遗产构成</span><h3>从单体到体系</h3><p>先辨识城、所、烽堠与炮台，再追问遗址之间的联系。</p><b>查看关联 →</b></button><button data-view="history"><span>二 / 历史空间</span><h3>让舆图与遗存对话</h3><p>辨别地名、地形与交通线索，保留古图自己的表达方式。</p><b>阅读舆图 →</b></button><button data-view="ai"><span>三 / 资料与解释</span><h3>带着问题回到证据</h3><p>检索遗址概况与沿革，让每一次阅读都有可以核对的出处。</p><b>查找资料 →</b></button></div></section><section class="experience-band"><div><span class="eyebrow">04 / INTERACTIVE LEARNING</span><h2>从阅读，走向参与。</h2><p>体验设施功能配对，或进入原有浙江舆图手势交互。</p></div><div><button class="light-btn" data-view="game">海防设施配对 ↗</button><button class="text-btn" data-view="gesture">进入舆图时空舱 →</button></div></section>`;
 $$('[data-home-city]').forEach(b=>b.onclick=()=>{homeCity=b.dataset.homeCity;$$('[data-home-city]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});renderHomeCity()});renderHomeCity();
}
function renderHomeCity(){const r=records.filter(x=>x['地级行政区']===homeCity);$('#home-city-records').innerHTML=`<div class="region-meta"><p><strong>${homeCity}</strong> · ${r.filter(hasCoord).length} 条有坐标 / ${r.length} 条记录</p><button id="open-home-city" class="secondary">探索${homeCity}全部遗产 ↗</button></div><div class="grid">${r.slice(0,3).map(x=>`<article class="card"><div class="eyebrow">${esc(x['遗产二级类型'])}</div><h3>${esc(x['遗址名称'])}</h3><p>${esc(summary(x).slice(0,95))}${summary(x).length>95?'…':''}</p><button class="secondary" data-detail="${x['遗产ID']}">阅读档案 →</button></article>`).join('')}</div>`;$('#open-home-city').onclick=()=>{query='';cityFilter.clear();cityFilter.add(homeCity);typeFilter.clear();explorePage=0;navigate('explore')}}
function gestureView(){
 $('#main').innerHTML=`<section class="page">${heading('TIME CAPSULE','浙江舆图 · 手势交互','连接仓库已有的浙江舆图交互。新窗口打开可获得更大的体验空间。')}<div class="note">原交互使用 Three.js 与 MediaPipe，需要联网。你可以选择示例视频，或在自己的浏览器中主动允许摄像头。此页面不会自动开启摄像头。</div><div class="toolbar"><a class="primary" href="${esc(config.gestureUrl||'https://yueee-0305.github.io/zhedong_Yutu/')}" target="_blank" rel="noreferrer">在新窗口打开原交互 ↗</a><button id="embed-gesture" class="secondary">在本页载入</button></div><div id="gesture-frame"></div></section>`;
 $('#embed-gesture').onclick=()=>{$('#gesture-frame').innerHTML=`<iframe title="明代浙江舆图手势交互" src="${esc(config.gestureUrl||'https://yueee-0305.github.io/zhedong_Yutu/')}" allow="camera; fullscreen" referrerpolicy="strict-origin-when-cross-origin" style="width:100%;height:70vh;border:1px solid var(--line)"></iframe>`;$('#embed-gesture').disabled=true;};
}

function exportRecords(){
 const keys=['遗产ID','遗址名称','地级行政区','区县','海防体系','遗产二级类型','经度','纬度','坐标系','定位精度','数据审核状态'];
 const csvCell=x=>'"'+String(x??'').replace(/^[=+@-]/,m=>"'"+m).replaceAll('"','""')+'"';
 const csv='\ufeff'+[keys,...filtered().map(r=>keys.map(k=>r[k]))].map(row=>row.map(csvCell).join(',')).join('\r\n');
 const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='heritage-filtered.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
function learnView(){
 const topics=[['军事聚落体系','从驻防空间理解城址','关注城墙、城门、街巷与驻防活动之间的联系。先分清“遗址类型”“军事建制”和今天的遗产边界。'],['烽传体系','看见与传递','从瞭望位置、警报传递和设施关联理解烽传。距离接近不能直接证明存在历史通信关系。'],['沿海防御体系','阅读海岸上的防御','结合海口、水道与地形观察设施的布局；再用史料解释其用途与变化。'],['内陆防御体系','海防与腹地的联系','研究关隘、交通和聚落之间的联系。不要仅凭今天的海岸距离判断遗址历史功能。'],['社会人文','从遗存看见地方社会','将祠庙、碑刻、人物与事件放回具体史料中，区分纪念叙事与可核验事实。']];
 $('#main').innerHTML=`<section class="page">${heading('HERITAGE LEARNING','先理解概念，再走进遗址','五组阅读线索，对应数据库既有分类。概念提示为教学整理，具体史实以档案证据为准。')}<div class="grid">${topics.map(([type,title,desc],i)=>`<article class="card"><div class="number">0${i+1}</div><h2>${title}</h2><p>${desc}</p><span class="tag">${records.filter(r=>r['海防体系']===type).length} 条关联记录</span><div class="card-bottom"><button class="primary" data-learn-type="${type}">查看案例 →</button></div></article>`).join('')}</div></section>`;
 $$('[data-learn-type]').forEach(b=>b.onclick=()=>{query='';cityFilter.clear();typeFilter.clear();typeFilter.add(b.dataset.learnType);explorePage=0;navigate('explore')});
}
function route(){
 const hash=location.hash.slice(1);if(hash.startsWith('heritage/')){let id;try{id=decodeURIComponent(hash.slice(9))}catch{id=''};navigate('explore');if(get(id))showDetail(id);else $('#cards').innerHTML='<div class="empty">未找到该遗产 ID，请在上方搜索。</div>';return;}
 const views=['home','map','explore','history','system','ai','game','guide','learn','gesture'];navigate(views.includes(hash)?hash:'home');
}
async function init(){
 try{
  let payload=window.ATLAS_DATA;
  if(!payload){const [catalog,boundary]=await Promise.all([fetch('data.json').then(r=>r.json()),fetch('zhejiang.json').then(r=>r.json())]);payload={catalog,boundary,media:[],config:{}};}
  db=payload.catalog;db.boundary=payload.boundary;config=payload.config||{};media=payload.media||[];records=db['01_遗产主表'];relations=db['02_遗址关系表'];
  $('footer span:nth-child(2)').textContent=`开源平台 v${config.version||'0.2.0'} / ${records.length} 条记录 · 坐标与史料待复核`;
  if(config.repositoryUrl&&/^https:\/\/github\.com\//.test(config.repositoryUrl)){$('#repo-link').href=config.repositoryUrl;$('#repo-link').hidden=false;}
  route();
 }catch(e){$('#main').innerHTML='<section class="page"><h1>资料加载暂未完成</h1><p>请使用完整源码包中的 dist/offline.html 直接打开，或按 README 启动本地服务。</p><button class="primary" onclick="location.reload()">重新加载</button></section>';console.error(e)}
}
window.addEventListener('hashchange',()=>{if(db)route()});
init();
